# Generated by Django 4.2.7 on 2023-12-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio_Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('moderado', 'Moderado'), ('critico', 'Critico')], default='moderado', max_length=10, verbose_name='Nivel de Acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Episodios_creados', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Episodios_propios_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parametro', models.CharField(blank=True, max_length=255, verbose_name='Parametro medido')),
                ('valor', models.FloatField(verbose_name='Valor de la Medicion')),
                ('unidades', models.CharField(blank=True, max_length=20, verbose_name='Unidades de la Medicion')),
                ('id_dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dipositivo_medidor', to='base.dispositivo_medico')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(blank=True, max_length=100, verbose_name='Rol')),
                ('permisos', models.CharField(choices=[('sin autorizacion', 'Sin Autorizacion'), ('visualizar historia clinica', 'Visualizar Historia Clinica'), ('visualizar notificaciones', 'Nisualizar Notificaciones'), ('visualizar alarmas', 'Visualizar Alarmas'), ('visualizar empleados', 'Visualizar Empleados'), ('editar empleados', 'Editar Empleados'), ('eliminar empleados', 'Eliminar Empleados'), ('crear empleados', 'Crear Empleados'), ('contratar empleados', 'Contratar Empleados'), ('despedir empleados', 'Despedir Empleados'), ('crear dispositivos', 'Crear Dispositivos'), ('configurar dispositivos', 'Configurar Dispositivos'), ('asignar cuidador', 'Asignar Cuidador'), ('reemplazar cuidador', 'Reempleazar Cuidador'), ('definir episodios medicos', 'Definir Episodios Medicos'), ('habilitar familiar', 'Habilitar Familiar')], default='sin autorizacion', max_length=255, verbose_name='Permisos permitidos')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', models.CharField(max_length=255, verbose_name='Permisos')),
                ('temporal', models.BooleanField(default=False, verbose_name='Temporal')),
                ('tipo_acceso', models.CharField(choices=[('acesso completo', 'Acceso Completo'), ('acceso parcial', 'Acceso Parcial'), ('acceso por rol', 'Acceso por Rol'), ('acceso solo lectura', 'Acceso Solo Lectura'), ('acceso de emergencia', 'Acceso de Emergencia'), ('sin acceso', 'Sin Acceso')], default='sin acceso', max_length=50, verbose_name='Tipos de Acceso')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(blank=True, max_length=255, verbose_name='Parametro a verificar')),
                ('valor_min', models.FloatField(blank=True, null=True, verbose_name='Valor minimo')),
                ('valor_max', models.FloatField(blank=True, null=True, verbose_name='Valor maximo')),
                ('unidades', models.CharField(blank=True, max_length=20, verbose_name='Unidades de la Medicion')),
            ],
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='num_seguro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Seguro'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion del Registro')),
                ('id_historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.historia_clinica')),
                ('id_medicion', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Registro_medidas', to='base.medicion')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de notificacion')),
                ('mensaje', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Fue leido?')),
                ('id_episodio_medico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.episodio_medico', verbose_name='Episodio Medico disparador')),
                ('id_paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paciente_notificacion', to=settings.AUTH_USER_MODEL)),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Receptor de Notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio_Revisa_Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('revisada_por_alarma', models.BooleanField(blank=True, default=False)),
                ('revisada_por_notificacion', models.BooleanField(blank=True, default=False)),
                ('episodio_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviso_medicion', to='base.episodio_medico')),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicion_revisada', to='base.medicion')),
            ],
        ),
        migrations.AddField(
            model_name='episodio_medico',
            name='id_rango',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rango_medidas', to='base.rango'),
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alarma')),
                ('mensaje', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Fue leido?')),
                ('id_episodio_medico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.episodio_medico', verbose_name='Episodio Medico disparador')),
                ('id_paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paciente_alarma', to=settings.AUTH_USER_MODEL)),
                ('id_paramedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paramedico asignado')),
            ],
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='nivel_visualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_visualizacion', to='base.nivel_visualizacion'),
        ),
    ]
