# Generated by Django 4.2.7 on 2023-12-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_episodio_medico_medicion_nivel_autorizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_historia_clinica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.historia_clinica'),
        ),
    ]
