# Generated by Django 4.2.7 on 2023-11-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='lastname',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_type',
            new_name='Tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='state',
        ),
    ]
