# Generated by Django 4.2.7 on 2023-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_empleado',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Familiar', 'Familiar'), ('Empleado de Salud', 'Empleado de Salud')], default=None, max_length=20),
        ),
    ]
