# Generated by Django 4.2.7 on 2023-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_lastname_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
