# Generated by Django 4.2.7 on 2023-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_usuario_tipo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_empleado',
            field=models.CharField(choices=[('Medico', 'Medico'), ('Cuidador', 'Cuidador'), ('Paramedico', 'Paramedico'), ('Empleado de Salud', 'Empleado de Salud')], default='Empleado de Salud', max_length=20),
        ),
    ]
