# Generated by Django 4.2.7 on 2023-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_usuario_familiares_usuario_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_medico',
            field=models.BooleanField(default=False),
        ),
    ]
